services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - models-onnx

#  model-text2text:
#    build: ./models/model-text2text
#    ports:
#      - "8503:8503"
#    volumes:
#      - huggingface_cache:/root/.cache/huggingface

  models-onnx:
    build: ./models/models-onnx
    ports:
      - "8504:8504"

volumes:
  huggingface_cache:
