services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - models-onnx

  models-onnx:
    build: ./models/models-onnx
    ports:
      - "8504:8504"

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_build:/app/dist
    command: npm run build

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  frontend_build:
  huggingface_cache:
